title: RKB SDET Blog
email: your-email@example.com
description: >-
  A blog about Software Testing, Selenium, Postman, and QA automation.
baseurl: "/rkb-sdet"
url: "https://rkb-sdet.github.io"
github_username: rkb-sdet

# Build settings
theme: minima

plugins:
  - jekyll-feed
  # - jekyll-archives    # Archives plugin ko hata diya

# jekyll-archives ka configuration hatao pura kyonki plugin disabled hai
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#     - years
#     - months
#   layouts:
#     category: category
#     tag: tag
#     year: archive
#     month: archive
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/
#     year: /archives/:year/
#     month: /archives/:year/:month/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
